### PR TITLE
Allow noscript fallback to be disabled

### PR DESCRIPTION
**Pull request by benbalter**
Fixes https://github.com/jekyll/jekyll-gist/issues/17.
Fixes https://github.com/jekyll/jekyll-gist/issues/26.

### CODE REVIEW

**Comment by parkr** [comment]
@benbalter Great! Just needs a test. Thank you!

**Comment by benbalter** [comment]
> Great! Just needs a test

Done (with docs too!)

**Comment by parkr** [comment]
LGTM. Once CI gives the :green_heart:, we can merge.

**Comment by parkr** [comment]
@benbalter To fix CI, `gist` must be defined in your block like `output`.

 ```ruby
let(:gist) { "mattr-/24081a1d93d2898ecf0f" } # choose a different ID if you want :)
```

**Pull request merged**
